version: "3.8"

services:
  murmur:
    image: goofball222/murmur
    container_name: murmur
    ports:
      - "33433:33433"
      - "33433:33433/udp"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./murmur/cert:/opt/murmur/cert
      - ./murmur/config:/opt/murmur/config
      - ./murmur/data:/opt/murmur/data
      - ./murmur/log:/opt/murmur/log
    environment:
      - TZ=UTC
    networks:
      - murmur
    restart: unless-stopped

  quakejs:
    container_name: quakejs
    ports: 
      - "27960:27960"
      - "27960:27960/udp"
      - "27950:27950"
    volumes:
      - quake_data:/usr/src
    build:
      context: ./quake
      dockerfile: Dockerfile
    networks:
      - quake
    restart: unless-stopped
      
  caddy:
    image: caddy:2-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    build:
      context: ./caddy
      dockerfile: Dockerfile
    networks:
      - caddy
    restart: unless-stopped
  
  minecraft:
    container_name: minecraft
    ports:
      - "19132:19132"
      - "19132:19132/udp"
      - "19133:19133"
      - "19133:19133/udp"
      - "62106:62106"
      - "62106:62106/udp"
      - "62107:62107"
      - "62107:62107/udp"
    volumes:
      - mc_data:/usr/src
    build:
      context: ./minecraft
      dockerfile: Dockerfile
    networks:
      - minecraft
    restart: unless-stopped

volumes:
  quake_data:
  caddy_data:
  caddy_config:
  mc_data:
  
networks:
  murmur:
  quake:
  caddy:
  minecraft:

    
